ALTER TABLE users
    ADD COLUMN IF NOT EXISTS b30_avg DECIMAL(6,2) NOT NULL DEFAULT 0.00;

ALTER TABLE records
    ADD COLUMN IF NOT EXISTS song_id BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS music_difficulty_id BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS music_achievement_id BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS play_level INT NULL,
    ADD COLUMN IF NOT EXISTS score_value DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_records_music_difficulty_id ON records (music_difficulty_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_records_user_difficulty ON records (user_id, music_difficulty_id);

CREATE TABLE IF NOT EXISTS b30_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    record_id BIGINT UNSIGNED NOT NULL,
    `rank` INT UNSIGNED NOT NULL,
    score_value DECIMAL(6,2) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_b30_user_rank (user_id, `rank`),
    KEY idx_b30_user (user_id),
    KEY idx_b30_record (record_id),
    CONSTRAINT fk_b30_user FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_b30_record FOREIGN KEY (record_id) REFERENCES records(id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

